version: 0.2
env:
  parameter-store:
    #CODEARTIFACT_AUTH_TOKEN: codeartifact-token
    dbhost: RDS-Endpoint
    dbuser: RDSUSER
    dbpass: RDSPASS
phases:
  install:
    runtime-versions:
      java: corretto17
      # I am using CodeBuild 7.0
      #java: corretto8
    commands:
      - cp ./settings.xml /root/.m2/settings.xml
      # do the export during the CodeBuild process not as a parameter. Comment out the parameter store entry above
      # the CODEARTIFACT_AUTH_TOKEN is ephemeral and must do it this way.
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain dmastrop --domain-owner 725291656587 --region us-east-1 --query authorizationToken --output text`
  pre_build:
    commands:
    # these update the application properties with the RDS endpoint and login credentials so that the tomcat server can connect to the backend RDS
      - sed -i "s/jdbc.password=admin123/jdbc.password=$dbpass/" src/main/resources/application.properties
      - sed -i "s/jdbc.username=admin/jdbc.username=$dbuser/" src/main/resources/application.properties
      - sed -i "s/db01:3306/$dbhost:3306/" src/main/resources/application.properties
      - apt-get update
      - apt-get install -y jq
      - wget https://downloads.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz
      - tar xzf apache-maven-3.8.8-bin.tar.gz
      - ln -s apache-maven-3.8.8 maven
  build:
    commands:
    # build the .war vprofile app 
      - mvn clean install -DskipTests
artifacts:
  files:
     - '**/*'
     # instead of uploading .war, we are uploading onto beanstalk the content of this directory
  base-directory: 'target/vprofile-v2'
